version: 1
default_branch: main
repositories:
  cli:
    visibility: public
    remote: https://github.com/devidevio/gitone.git
    paths:
      - .editorconfig
      - .github/FUNDING.yml
      - .github/ISSUE_TEMPLATE/**
      - .github/PULL_REQUEST_TEMPLATE.md
      - .github/dependabot.yml
      - .github/workflows/ci.yml
      - .github/workflows/release-cut.yml
      - .github/workflows/release.yml
      - .gitignore
      - .gitone.yml
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - README.md
      - SECURITY.md
      - cmd/**
      - docs/RECONFIGURATION.md
      - docs/TUTORIAL.md
      - docs/USAGE.md
      - docs/assets/demo.gif
      - editors/**
      - go.mod
      - go.sum
      - install.sh
      - internal/**
      - scripts/**
